apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-workflow
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    name: deis-workflow
  template:
    metadata:
      labels:
        name: deis-workflow
    spec:
      containers:
        - name: deis-workflow
          image: quay.io/deisci/workflow:v2-beta
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          env:
            - name: DEIS_DATABASE_SERVICE_HOST
              value: 
            - name: DEIS_DATABASE_USER
              value: deis
            - name: DEIS_DATABASE_PASSWORD
              value: changeme123
            - name: DEIS_REGISTRY_SERVICE_HOST
              value: 
            - name: DEIS_REGISTRY_SERVICE_PORT
              value: 5000
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: docker-builder-socket
              mountPath: /var/run/docker.sock
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
      volumes:
        - name: docker-builder-socket
          hostPath:
            path: /var/run/docker-builder.sock
        - name: minio-user
          secret:
            secretName: minio-user
